export const REMEMBER_ME = 'REMEMBER_ME';
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const REGISTER = 'REGISTER';

export const SET_STATUS_REQUEST = `SET_STATUS_REQUEST`;
export const SET_ERROR_REQUEST = `SET_ERROR_REQUEST`;

export const REQUEST_SKILLS = `REQUEST_SKILLS`;
export const RECEIVE_SKILLS = `RECEIVE_SKILLS`;
