export const REMEMBER_ME = 'REMEMBER_ME';
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';

export const USER_ADD_SKILL = 'USER_ADD_SKILL';
export const USER_REMOVE_SKILL = 'USER_REMOVE_SKILL';
export const USER_REORDER_SKILL = 'USER_REORDER_SKILL';

export const SET_STATUS_REQUEST = 'SET_STATUS_REQUEST'
export const SET_ERROR_REQUEST = 'SET_ERROR_REQUEST'
